name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - stage
  pull_request:
    branches:
      - main
      - stage

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Skip tests
      run: echo "No tests yet"

    - name: Skip build
      run: echo "No build step yet"

    - name: Deploy public folder
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stage'
      uses: peaceiris/actions-gh-pages@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public